name: Test & Publish to PyPI

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"  # Trigger publish on tags like v0.1.0, v1.2.3, etc.
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests (Python 3.10 & 3.11)
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install your library in editable mode, including [test] extras
      - name: Install project with test extras
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .[test]

      # Create the EDGAR data directory if your tests need it
      - name: Create EDGAR data directory
        run: mkdir -p /home/runner/.edgar

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -v -n auto

  publish:
    # Only run this job when a tag starting with 'v' is pushed
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ test ]
    runs-on: ubuntu-latest

    # Permissions required for OIDC-based publishing
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build package
        run: |
          python -m pip install --upgrade pip setuptools wheel build
          python -m build

      - name: Publish via OIDC to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          package-name: "edgar-analytics"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
